pipeline {


  agent {
   kubernetes {
      yaml """
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.5.4-jdk-8-slim
      command: ["tail", "-f", "/dev/null"]  
      imagePullPolicy: Always 
      resources:  
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
"""
     defaultContainer 'maven'
    }
  }
    environment {
        MAVEN_ADDITIONAL_TARGETS = "${mavenAdditionalTargets}"
    }
    stages {
        stage('Test') {
            steps {
                sh 'env'
            }
        }
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean verify -C -e --show-version'
                }
            }
        }
    }

}
